# Generated by Django 6.1.1 on 2026-09-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("texts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="texts.text",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="mailings",
                        to="clients.client",
                        verbose_name="получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["-start_at", "status"],
            },
        ),
        migrations.CreateModel(
            name="BulkMailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        default="failed",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Текст ошибки/ответа от SMTP-сервера (может быть длинным)",
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="bulkmailing.bulkmailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bulkmailing",
            index=models.Index(fields=["status"], name="bulkmailing_status_814fb5_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkmailing",
            index=models.Index(
                fields=["start_at"], name="bulkmailing_start_a_9cbbdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkmailing",
            index=models.Index(fields=["end_at"], name="bulkmailing_end_at_c781ca_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkmailingattempt",
            index=models.Index(
                fields=["mailing", "-attempted_at"],
                name="bulkmailing_mailing_5148da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkmailingattempt",
            index=models.Index(
                fields=["status", "-attempted_at"], name="bulkmailing_status_285147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkmailingattempt",
            index=models.Index(
                fields=["attempted_at"], name="bulkmailing_attempt_f234fd_idx"
            ),
        ),
    ]
