# Generated by Django 6.1.1 on 2026-09-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulkmailing", "0001_initial"),
        ("clients", "0002_alter_client_options_alter_client_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkmailing",
            options={
                "ordering": ["-start_at", "status"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="bulkmailing",
            name="recipients",
            field=models.ManyToManyField(
                related_name="mailings", to="clients.client", verbose_name="Получатели"
            ),
        ),
    ]
