# Generated by Django 6.1.1 on 2026-09-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulkmailing", "0003_bulkmailing_owner_and_disabled"),
        ("clients", "0003_client_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkmailingattempt",
            options={
                "ordering": ["-attempted_at"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AddField(
            model_name="bulkmailingattempt",
            name="error_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Код ошибки SMTP"
            ),
        ),
        migrations.AddField(
            model_name="bulkmailingattempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_attempts",
                to="clients.client",
                verbose_name="Получатель",
            ),
        ),
    ]
