# Generated by Django 6.1.1 on 2026-09-27 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulkmailing", "0004_bulkmailing_attempt_error_code_and_recipient"),
        ("clients", "0003_client_owner"),
        ("texts", "0003_text_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkmailing",
            name="next_run_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Рассчитывается автоматически после каждой отправки",
                null=True,
                verbose_name="Следующая отправка",
            ),
        ),
        migrations.AddField(
            model_name="bulkmailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("once", "Однократно"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                ],
                default="once",
                max_length=10,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkmailing",
            index=models.Index(
                fields=["next_run_at"], name="bulkmailing_next_ru_90f450_idx"
            ),
        ),
    ]
