# Generated by Django 6.1.1 on 2026-09-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name": "text",
                "verbose_name_plural": "texts",
                "ordering": ["title"],
            },
        ),
    ]
