# Generated by Django 6.1.1 on 2026-09-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="text",
            options={
                "ordering": ["title"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterField(
            model_name="text",
            name="text",
            field=models.TextField(verbose_name="Тело письма"),
        ),
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Тема письма"),
        ),
    ]
